# This file contains various mappings used by the API

_TERSE_TO_AGENCY_LABELS = {
     "piid": "PIID",
     "awarding_sub_tier_agency_c": "AwardingSubTierAgencyCode",
     "awarding_sub_tier_agency_n": "AwardingSubTierAgencyName",
     "awarding_agency_code": "AwardingAgencyCode",
     "awarding_agency_name": "AwardingAgencyName",
     "parent_award_id": "ParentAwardId",
     "award_modification_amendme": "AwardModificationAmendmentNumber",
     "type_of_contract_pricing": "TypeOfContractPricing",
     "contract_award_type": "ContractAwardType",
     "naics": "NAICS",
     "naics_description": "NAICS_Description",
     "awardee_or_recipient_uniqu": "AwardeeOrRecipientUniqueIdentifier",
     "ultimate_parent_legal_enti": "UltimateParentLegalEntityName",
     "ultimate_parent_unique_ide": "UltimateParentUniqueIdentifier",
     "award_description": "AwardDescription",
     "place_of_performance_zip4a": "PrimaryPlaceOfPerformanceZIP+4",
     "place_of_performance_congr": "PrimaryPlaceOfPerformanceCongressionalDistrict",
     "awardee_or_recipient_legal": "AwardeeOrRecipientLegalEntityName",
     "legal_entity_city_name": "LegalEntityCityName",
     "legal_entity_state_code": "LegalEntityStateCode",
     "legal_entity_zip4": "LegalEntityZIP+4",
     "legal_entity_congressional": "LegalEntityCongressionalDistrict",
     "legal_entity_address_line1": "LegalEntityAddressLine1",
     "legal_entity_address_line2": "LegalEntityAddressLine2",
     "legal_entity_address_line3": "LegalEntityAddressLine3",
     "legal_entity_country_code": "LegalEntityCountryCode",
     "legal_entity_country_name": "LegalEntityCountryName",
     "period_of_performance_star": "PeriodOfPerformanceStartDate",
     "period_of_performance_curr": "PeriodOfPerformanceCurrentEndDate",
     "period_of_perf_potential_e": "PeriodOfPerfPotentialEndDate",
     "ordering_period_end_date": "OrderingPeriodEndDate",
     "action_date": "ActionDate",
     "action_type": "ActionType",
     "federal_action_obligation": "FederalActionObligation",
     "current_total_value_award": "CurrentTotalValueAwardAmount",
     "potential_total_value_awar": "PotentialTotalValueAwardAmount",
     "funding_sub_tier_agency_co": "FundingSubTierAgencyCode",
     "funding_sub_tier_agency_na": "FundingSubTierAgencyName",
     "funding_office_code": "FundingOfficeCode",
     "funding_office_name": "FundingOfficeName",
     "awarding_office_code": "AwardingOfficeCode",
     "awarding_office_name": "AwardingOfficeName",
     "referenced_idv_agency_iden": "Referenced IDV Agency Identifier",
     "funding_agency_code": "FundingAgencyCode",
     "funding_agency_name": "FundingAgencyName",
     "place_of_performance_locat": "PrimaryPlaceOfPerformanceLocationCode",
     "place_of_performance_state": "PrimaryPlaceOfPerformanceStateCode",
     "place_of_perform_country_c": "PrimaryPlaceOfPerformanceCountryCode",
     "idv_type": "IDV_Type",
     "vendor_doing_as_business_n": "Vendor Doing As Business Name",
     "vendor_phone_number": "Vendor Phone Number",
     "vendor_fax_number": "Vendor Fax Number",
     "multiple_or_single_award_i": "Multiple or Single Award IDV",
     "type_of_idc": "Type of IDC",
     "a_76_fair_act_action": "A-76 FAIR Act Action",
     "dod_claimant_program_code": "DoD Claimant Program Code",
     "clinger_cohen_act_planning": "Clinger-Cohen Act Planning Compliance",
     "commercial_item_acquisitio": "Commercial Item Acquisition Procedures",
     "commercial_item_test_progr": "Commercial Item Test Program",
     "consolidated_contract": "Consolidated Contract",
     "contingency_humanitarian_o": "Contingency Humanitarian or Peacekeeping Operation",
     "contract_bundling": "Contract Bundling",
     "contract_financing": "Contract Financing",
     "contracting_officers_deter": "Contracting Officer's Determination of Business Size",
     "cost_accounting_standards": "Cost Accounting Standards Clause",
     "cost_or_pricing_data": "Cost or Pricing Data",
     "country_of_product_or_serv": "Country of Product or Service Origin",
     "davis_bacon_act": "Davis Bacon Act",
     "evaluated_preference": "Evaluated Preference",
     "extent_competed": "Extent Competed",
     "fed_biz_opps": "FedBizOpps",
     "foreign_funding": "Foreign Funding",
     "government_furnished_equip": "Government Furnished Equipment GFE and Government Furnished Property GFP",
     "information_technology_com": "Information Technology Commercial Item Category",
     "interagency_contracting_au": "Interagency Contracting Authority",
     "local_area_set_aside": "Local Area Set Aside",
     "major_program": "Major program",
     "purchase_card_as_payment_m": "Purchase Card as Payment Method",
     "multi_year_contract": "Multi Year Contract",
     "national_interest_action": "National Interest Action",
     "number_of_actions": "Number of Actions",
     "number_of_offers_received": "Number of Offers Received",
     "other_statutory_authority": "Other Statutory Authority",
     "performance_based_service": "Performance-Based Service Acquisition",
     "place_of_manufacture": "Place of Manufacture",
     "price_evaluation_adjustmen": "Price Evaluation Adjustment Preference Percent Difference",
     "product_or_service_code": "Product or Service Code",
     "program_acronym": "Program Acronym",
     "other_than_full_and_open_c": "Other than Full and Open Competition",
     "recovered_materials_sustai": "Recovered Materials/Sustainability",
     "research": "Research",
     "sea_transportation": "Sea Transportation",
     "service_contract_act": "Service Contract Act",
     "small_business_competitive": "Small Business Competitiveness Demonstration Program",
     "solicitation_identifier": "Solicitation Identifier",
     "solicitation_procedures": "Solicitation Procedures",
     "fair_opportunity_limited_s": "Fair Opportunity Limited Sources",
     "subcontracting_plan": "Subcontracting Plan",
     "program_system_or_equipmen": "Program, System, or Equipment Code",
     "type_set_aside": "Type Set Aside",
     "epa_designated_product": "EPA-Designated Product",
     "walsh_healey_act": "Walsh Healey Act",
     "transaction_number": "Transaction Number",
     "sam_exception": "SAM Exception",
     "city_local_government": "City Local Government",
     "county_local_government": "County Local Government",
     "inter_municipal_local_gove": "Inter-Municipal Local Government",
     "local_government_owned": "Local Government Owned",
     "municipality_local_governm": "Municipality Local Government",
     "school_district_local_gove": "School District Local Government",
     "township_local_government": "Township Local Government",
     "us_state_government": "U.S. State Government",
     "us_federal_government": "U.S. Federal Government",
     "federal_agency": "Federal Agency",
     "federally_funded_research": "Federally Funded Research and Development Corp",
     "us_tribal_government": "U.S. Tribal Government",
     "foreign_government": "Foreign Government",
     "community_developed_corpor": "Community Developed Corporation Owned Firm",
     "labor_surplus_area_firm": "Labor Surplus Area Firm",
     "corporate_entity_not_tax_e": "Corporate Entity Not Tax Exempt",
     "corporate_entity_tax_exemp": "Corporate Entity Tax Exempt",
     "partnership_or_limited_lia": "Partnership or Limited Liability Partnership",
     "sole_proprietorship": "Sole Proprietorship",
     "small_agricultural_coopera": "Small Agricultural Cooperative",
     "international_organization": "International Organization",
     "us_government_entity": "U.S. Government Entity",
     "emerging_small_business": "Emerging Small business",
     "8a_program_participant": "8a Program Participant",
     "sba_certified_8_a_joint_ve": "SBA Certified 8 a Joint Venture",
     "dot_certified_disadvantage": "DoT Certified Disadvantaged Business Enterprise",
     "self_certified_small_disad": "Self-Certified Small Disadvantaged Business",
     "historically_underutilized": "Historically Underutilized Business Zone HUBZone Firm",
     "small_disadvantaged_busine": "Small Disadvantaged Business",
     "the_ability_one_program": "The AbilityOne Program",
     "historically_black_college": "Historically Black College or University",
     "1862_land_grant_college": "1862 Land grant College",
     "1890_land_grant_college": "1890 land grant College",
     "1994_land_grant_college": "1994 Land Grant College",
     "minority_institution": "Minority Institution",
     "private_university_or_coll": "Private University or College ",
     "school_of_forestry": "School of Forestry",
     "state_controlled_instituti": "State Controlled Institution of Higher Learning",
     "tribal_college": "Tribal College",
     "veterinary_college": "Veterinary College",
     "educational_institution": "Educational Institution",
     "alaskan_native_servicing_i": "Alaskan Native Servicing Institution",
     "community_development_corp": "Community Development Corporation",
     "native_hawaiian_servicing": "Native Hawaiian Servicing Institution",
     "domestic_shelter": "Domestic Shelter",
     "manufacturer_of_goods": "Manufacturer of Goods",
     "hospital_flag": "Hospital Flag",
     "veterinary_hospital": "Veterinary Hospital",
     "hispanic_servicing_institu": "Hispanic Servicing Institution",
     "foundation": "Foundation",
     "woman_owned_business": "Woman Owned business",
     "minority_owned_business": "Minority Owned Business",
     "women_owned_small_business": "Women Owned Small Business",
     "economically_disadvantaged": "Economically Disadvantaged Women Owned Small Business",
     "joint_venture_women_owned": "Joint Venture Women Owned Small Business",
     "joint_venture_economically": "Joint Venture Economically Disadvantaged Women Owned Small Business",
     "veteran_owned_business": "Veteran Owned Business",
     "service_disabled_veteran_o": "Service Disabled Veteran Owned Business",
     "contracts": "Contracts",
     "grants": "Grants",
     "receives_contracts_and_gra": "Receives Contracts and Grants",
     "airport_authority": "Airport Authority",
     "council_of_governments": "Council of Governments",
     "housing_authorities_public": "Housing Authorities Public/Tribal",
     "interstate_entity": "Interstate Entity",
     "planning_commission": "Planning Commission",
     "port_authority": "Port Authority",
     "transit_authority": "Transit Authority",
     "subchapter_s_corporation": "Subchapter S Corporation",
     "limited_liability_corporat": "Limited Liability Corporation",
     "foreign_owned_and_located": "Foreign Owned and Located",
     "american_indian_owned_busi": "American Indian Owned Business",
     "alaskan_native_owned_corpo": "Alaskan Native Owned Corporation or Firm",
     "indian_tribe_federally_rec": "Indian Tribe Federally Recognized",
     "native_hawaiian_owned_busi": "Native Hawaiian Owned Business",
     "tribally_owned_business": "Tribally Owned Business",
     "asian_pacific_american_own": "Asian Pacific American Owned business",
     "black_american_owned_busin": "Black American Owned Business",
     "hispanic_american_owned_bu": "Hispanic American Owned Business",
     "native_american_owned_busi": "Native American Owned Business",
     "subcontinent_asian_asian_i": "Subcontinent Asian Asian - Indian American Owned Business",
     "other_minority_owned_busin": "Other Minority Owned Business",
     "for_profit_organization": "For Profit Organization",
     "nonprofit_organization": "Nonprofit Organization",
     "other_not_for_profit_organ": "Other Not For Profit Organization",
     "us_local_government": "U.S. Local Government",
     "referenced_idv_modificatio": "Referenced IDV Modification Number",
     "undefinitized_action": "Undefinitized Action",
     "domestic_or_foreign_entity": "Domestic or Foreign Entity",
     "action_type": "ActionType",
     "adjustments_to_unobligated": "AdjustmentsToUnobligatedBalanceBroughtForward",
     "agency_identifier": "AgencyIdentifier",
     "allocation_transfer_agency": "AllocationTransferAgencyIdentifier",
     "assistance_type": "AssistanceType",
     "availability_type_code": "AvailabilityTypeCode",
     "award_report_month": "AwardReportMonth",
     "award_report_year": "AwardReportYear",
     "beginning_period_of_availa": "BeginningPeriodOfAvailability",
     "borrowing_authority_amount": "BorrowingAuthorityAmountTotal",
     "budget_authority_appropria": "BudgetAuthorityAppropriatedAmount",
     "budget_authority_available": "BudgetAuthorityAvailableAmountTotal",
     "budget_authority_unobligat": "BudgetAuthorityUnobligatedBalanceBroughtForward",
     "business_funds_indicator": "BusinessFundsIndicator",
     "business_types": "BusinessTypes",
     "by_direct_reimbursable_fun": "ByDirectReimbursableFundingSource",
     "cfda_number": "CFDA_Number",
     "cfda_number_and_title": "CFDA_NumberAndTitle",
     "cfda_title": "CFDA_Title",
     "contract_authority_amount": "ContractAuthorityAmountTotal",
     "correction_late_delete_ind": "CorrectionLateDeleteIndicator",
     "deobligations_recoveries_r": "DeobligationsRecoveriesRefundsByTAS",
     "deobligations_recov_by_awa": "DeobligationsRecoveriesRefundsOfPriorYearByAward",
     "deobligations_recov_by_pro": "DeobligationsRecoveriesRefundsOfPriorYearByProgramObjectClass",
     "ending_period_of_availabil": "EndingPeriodOfAvailability",
     "face_value_loan_guarantee": "FaceValueLoanGuarantee",
     "fain": "FAIN",
     "fiscal_year_and_quarter_co": "FiscalYearAndQuarterCorrection",
     "gross_outlay_amount_by_awa": "GrossOutlayAmountByAward",
     "gross_outlay_amount_by_pro": "GrossOutlayAmountByProgramObjectClass",
     "gross_outlay_amount_by_tas": "GrossOutlayAmountByTAS",
     "gross_outlays_delivered_or": "GrossOutlaysDeliveredOrdersPaidTotal",
     "gross_outlays_undelivered": "GrossOutlaysUndeliveredOrdersPrepaidTotal",
     "high_comp_officer_amount": "HighCompOfficerAmount",
     "high_comp_officer_first_na": "HighCompOfficerFirstName",
     "high_comp_officer_full_nam": "HighCompOfficerFullName",
     "high_comp_officer_last_nam": "HighCompOfficerLastName",
     "high_comp_officer_middle_i": "HighCompOfficerMiddleInitial",
     "legal_entity_city_code": "LegalEntityCityCode",
     "legal_entity_county_code": "LegalEntityCountyCode",
     "legal_entity_county_name": "LegalEntityCountyName",
     "legal_entity_foreign_city": "LegalEntityForeignCityName",
     "legal_entity_foreign_posta": "LegalEntityForeignPostalCode",
     "legal_entity_foreign_provi": "LegalEntityForeignProvinceName",
     "legal_entity_state_name": "LegalEntityStateName",
     "legal_entity_zip5": "LegalEntityZIP5",
     "legal_entity_zip_last4": "LegalEntityZIPLast4",
     "main_account_code": "MainAccountCode",
     "non_federal_funding_amount": "NonFederalFundingAmount",
     "object_class": "ObjectClass",
     "obligations_delivered_orde": "ObligationsDeliveredOrdersUnpaidTotal",
     "obligations_incurred_by_pr": "ObligationsIncurredByProgramObjectClass",
     "obligations_incurred_byawa": "ObligationsIncurredTotalByAward",
     "obligations_incurred_total": "ObligationsIncurredTotalByTAS",
     "obligations_undelivered_or": "ObligationsUndeliveredOrdersUnpaidTotal",
     "original_loan_subsidy_cost": "OriginalLoanSubsidyCost",
     "other_budgetary_resources": "OtherBudgetaryResourcesAmount",
     "place_of_performance_addre": "PrimaryPlaceOfPerformanceAddressLine1",
     "place_of_performance_city": "PrimaryPlaceOfPerformanceCityName",
     "place_of_performance_code": "PrimaryPlaceOfPerformanceCode",
     "place_of_perform_country_n": "PrimaryPlaceOfPerformanceCountryName",
     "place_of_perform_county_na": "PrimaryPlaceOfPerformanceCountyName",
     "place_of_performance_forei": "PrimaryPlaceOfPerformanceForeignLocationDescription",
     "place_of_perform_state_nam": "PrimaryPlaceOfPerformanceStateName",
     "place_of_performance_zip4": "PrimaryPlaceOfPerformanceZIP+4",
     "prime_award_report_id": "PrimeAwardReportId",
     "program_activity_code": "ProgramActivityCode",
     "program_activity_name": "ProgramActivityName",
     "rec_model_question1": "RecModelQuestion1",
     "rec_model_question2": "RecModelQuestion2",
     "record_type": "RecordType",
     "sai_number": "SAI_Number",
     "spending_authority_from_of": "SpendingAuthorityFromOffsettingCollectionsAmountTotal",
     "status_of_budgetary_resour": "StatusOfBudgetaryResourcesTotal",
     "sub_account_code": "SubAccountCode",
     "subawardee_business_type": "SubawardeeBusinessType",
     "sub_awardee_or_recipient_l": "SubAwardeeOrRecipientLegalEntityName",
     "sub_awardee_or_recipient_u": "SubAwardeeOrRecipientUniqueIdentifier",
     "sub_awardee_ultimate_paren": "SubAwardeeUltimateParentLegalEntityName",
     "sub_awardee_ultimate_pa_id": "SubAwardeeUltimateParentUniqueIdentifier",
     "subaward_number": "SubawardNumber",
     "subcontract_award_amount": "SubcontractAwardAmount",
     "total_funding_amount": "TotalFundingAmount",
     "transaction_obligated_amou": "TransactionObligatedAmount",
     "unobligated_balance": "UnobligatedBalance",
     "uri": "URI",
     "ussgl480100_undelivered_or": "USSGL480100_UndeliveredOrdersObligationsUnpaid",
     "ussgl480200_undelivered_or": "USSGL480200_UndeliveredOrdersObligationsPrepaidAdvanced",
     "ussgl483100_undelivered_or": "USSGL483100_UndeliveredOrdersObligationsTransferredUnpaid",
     "ussgl483200_undelivered_or": "USSGL483200_UndeliveredOrdersObligationsTransferredPrepaidAdvanced",
     "ussgl487100_downward_adjus": "USSGL487100_DownwardAdjustmentsOfPriorYearUnpaidUndeliveredOrdersObligationsRecoveries",
     "ussgl487200_downward_adjus": "USSGL487200_DownwardAdjustmentsOfPriorYearPrepaidAdvancedUndeliveredOrdersObligationsRefundsCollected",
     "ussgl488100_upward_adjustm": "USSGL488100_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsUnpaid",
     "ussgl488200_upward_adjustm": "USSGL488200_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsPrepaidAdvanced",
     "ussgl490100_delivered_orde": "USSGL490100_DeliveredOrdersObligationsUnpaid",
     "ussgl490200_delivered_orde": "USSGL490200_DeliveredOrdersObligationsPaid ",
     "ussgl490800_authority_outl": "USSGL490800_AuthorityOutlayedNotYetDisbursed",
     "ussgl493100_delivered_orde": "USSGL493100_DeliveredOrdersObligationsTransferredUnpaid",
     "ussgl497100_downward_adjus": "USSGL497100_DownwardAdjustmentsOfPriorYearUnpaidDeliveredOrdersObligationsRecoveries",
     "ussgl497200_downward_adjus": "USSGL497200_DownwardAdjustmentsOfPriorYearPaidDeliveredOrdersObligationsRefundsCollected",
     "ussgl498100_upward_adjustm": "USSGL498100_Upward AdjustmentsOfPriorYearDeliveredOrdersObligationsUnpaid  ",
     "ussgl498200_upward_adjustm": "USSGL498200_UpwardAdjustmentsOfPriorYearDeliveredOrdersObligationsPaid "
}

# How the award response is grouped
_AWARD_RESPONSE_MAP = {
    "VendorFaxNumber": "recipient_info",
    "LegalEntityCityName": "recipient_info",
    "LegalEntityZip4": "recipient_info",
    "ParentAwardId": "linking_procurement",
    "AgencyIdentifier": "tas",
    "LegalEntityStateCode": "recipient_info",
    "URI": "linking_financial_assistance",
    "CurrentTotalValueOfAward": "award_action",
    "IDV Type": "indirect_delivery_vehicle_specific_charactersitcs",
    "PIID": "linking_procurement",
    "NorthAmericanIndustrialClassificationSystemCode": "award_type",
    "SubAccountCode": "tas",
    "TransactionObligatedAmount": "transaction_obligated_amount",
    "LegalEntityCountryCode": "recipient_info",
    "PrimaryPlaceOfPerformanceZip4": "place_of_performance",
    "PeriodOfPerformanceStartDate": "award_dates",
    "AwardDescription": "award_info",
    "ReferencedIDVAgencyIdentifier": "indirect_delivery_vehicle_specific_charactersitcs",
    "AwardingOfficeCode": "awarding_agency",
    "ActionDate": "award_action",
    "AwardingSubTierAgencyCode": "awarding_agency",
    "AwardModificationAmendmentNumber": "award_modification",
    "PotentialTotalValueOfAward": "award_action",
    "AllocationTransferAgencyIdentifier": "tas",
    "AwardType": "award_action",
    "PrimaryPlaceofPerformanceCongressionalDistrict": "place_of_performance",
    "PeriodOfPerformanceCurrentEndDate": "award_dates",
    "AvailabilityTypeCode": "tas",
    "MainAccountCode": "tas",
    "LegalEntityCongressionalDistrict": "recipient_info",
    "AwardeeOrRecipientUniqueIdentifier": "award_recipient",
    "FAIN": "linking_financial_assistance",
    "AwardeeOrRecipientLegalEntityName": "award_recipient",
    "FundingOfficeCode": "funding_agency",
    "VendorPhoneNumber": "recipient_info",
    "FederalActionObligation": "award_action",
    "PeriodOfPerformancePotentialEndDate": "award_dates",
    "FundingSubTierAgencyCode": "funding_agency",
    "EndingPeriodOfAvailability": "tas",
    "VendorDoingAsBusinessName": "award_recipient",
    "BeginningPeriodOfAvailability": "tas",
    "LegalEntityAddressLine2": "recipient_info",
    "LegalEntityAddressLine1": "recipient_info",
    "VendorAddressLine3": "recipient_info",
    "TypeofIDC": "indirect_delivery_vehicle_specific_charactersitcs",
    "MultipleorSingleAwardIDV": "indirect_delivery_vehicle_specific_charactersitcs"
}

# How the financial response is grouped
_FINANCIAL_RESPONSE_MAP = {
    "BudgetAuthorityUnobligatedBalanceBroughtForward_FYB": "budget_authority",
    "AdjustmentsToUnobligatedBalanceBroughtForward_CPE": "budget_authority",
    "BudgetAuthorityAppropriatedAmount_CPE": "budget_authority",
    "OtherBudgetaryResourcesAmount_CPE": "budget_authority",
    "BudgetAuthorityAvailableAmountTotal_CPE": "budget_authority",
    "ObligationsIncurredTotalByTAS_CPE": "budgetary_resources",
    "GrossOutlayAmountByTAS_CPE": "budgetary_resources",
    "ContractAuthorityAmountTotal_CPE": "budget_authority",
    "BorrowingAuthorityAmountTotal_CPE": "budget_authority",
    "SpendingAuthorityfromOffsettingCollectionsAmountTotal_CPE": "budget_authority",
    "StatusOfBudgetaryResourcesTotal_CPE": "budgetary_resources",
    "AllocationTransferAgencyIdentifier": "tas",
    "AvailabilityTypeCode": "tas",
    "EndingPeriodOfAvailability": "tas",
    "BeginningPeriodOfAvailability": "tas",
    "AgencyIdentifier": "tas",
    "SubAccountCode": "tas",
    "MainAccountCode": "tas",
    "DeobligationsRecoveriesRefundsByTAS_CPE": "budgetary_resources",
    "UnobligatedBalance_CPE": "budgetary_resources",
    "DeobligationsRecoveriesRefundsdOfPriorYearByProgramObjectClass_CPE": "obligations_incurred",
    "GrossOutlayAmountByProgramObjectClass_CPE": "gross_outlays",
    "GrossOutlayAmountByProgramObjectClass_FYB": "gross_outlays",
    "GrossOutlaysDeliveredOrdersPaidTotal_FYB": "gross_outlays",
    "GrossOutlaysDeliveredOrdersPaidTotal_CPE": "gross_outlays",
    "GrossOutlaysUndeliveredOrdersPrepaidTotal_CPE": "gross_outlays",
    "GrossOutlaysUndeliveredOrdersPrepaidTotal_FYB": "gross_outlays",
    "ObligationsDeliveredOrdersUnpaidTotal_FYB": "obligations_incurred",
    "ObligationsDeliveredOrdersUnpaidTotal_CPE": "obligations_incurred",
    "ObligationsIncurredByProgramObjectClass_CPE": "obligations_incurred",
    "ObligationsUndeliveredOrdersUnpaidTotal_FYB": "obligations_incurred",
    "ObligationsUndeliveredOrdersUnpaidTotal_CPE": "obligations_incurred"
}
