# This file contains various mappings used by the API

_TERSE_TO_AGENCY_LABELS = {
    "allocation_transfer_agency": "AllocationTransferAgencyIdentifier",
    "responsible_agency_id": "AgencyIdentifier",
    "beginning_period_of_availa": "BeginningPeriodOfAvailability",
    "ending_period_of_availabil": "EndingPeriodOfAvailability",
    "availability_type_code": "AvailabilityTypeCode",
    "main_account_code": "MainAccountCode",
    "sub_account_code": "SubAccountCode",
    "budget_authority_unobligat_fyb": "BudgetAuthorityUnobligatedBalanceBroughtForward_FYB",
    "adjustments_to_unobligated_cpe": "AdjustmentsToUnobligatedBalanceBroughtForward_CPE",
    "budget_authority_appropria_cpe": "BudgetAuthorityAppropriatedAmount_CPE",
    "borrowing_authority_amount_cpe": "BorrowingAuthorityAmountTotal_CPE",
    "contract_authority_amount_cpe": "ContractAuthorityAmountTotal_CPE",
    "spending_authority_from_of_cpe": "SpendingAuthorityfromOffsettingCollectionsAmountTotal_CPE",
    "other_budgetary_resources_cpe": "OtherBudgetaryResourcesAmount_CPE",
    "budget_authority_available_cpe": "BudgetAuthorityAvailableAmountTotal_CPE",
    "gross_outlay_amount_by_tas_cpe": "GrossOutlayAmountByTAS_CPE",
    "obligations_incurred_total_cpe": "ObligationsIncurredTotalByTAS_CPE",
    "deobligations_recoveries_r_cpe": "DeobligationsRecoveriesRefundsByTAS_CPE",
    "unobligated_balance_cpe": "UnobligatedBalance_CPE",
    "status_of_budgetary_resour_cpe": "StatusOfBudgetaryResourcesTotal_CPE",
    "allocation_transfer_agency": "AllocationTransferAgencyIdentifier",
    "program_activity_name": "ProgramActivityName",
    "program_activity_code": "ProgramActivityCode",
    "object_class": "ObjectClass",
    "by_direct_reimbursable_fun": "ByDirectReimbursableFundingSource",
    "ussgl480100_undelivered_or_fyb": "USSGL480100_UndeliveredOrdersObligationsUnpaid_FYB",
    "ussgl480100_undelivered_or_cpe": "USSGL480100_UndeliveredOrdersObligationsUnpaid_CPE",
    "ussgl483100_undelivered_or_cpe": "USSGL483100_UndeliveredOrdersObligationsTransferredUnpaid_CPE",
    "ussgl488100_upward_adjustm_cpe": "USSGL488100_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsUnpaid_CPE",
    "obligations_undelivered_or_fyb": "ObligationsUndeliveredOrdersUnpaidTotal_FYB",
    "obligations_undelivered_or_cpe": "ObligationsUndeliveredOrdersUnpaidTotal_CPE",
    "ussgl490100_delivered_orde_fyb": "USSGL490100_DeliveredOrdersObligationsUnpaid_FYB",
    "ussgl490100_delivered_orde_cpe": "USSGL490100_DeliveredOrdersObligationsUnpaid_CPE",
    "ussgl493100_delivered_orde_cpe": "USSGL493100_DeliveredOrdersObligationsTransferredUnpaid_CPE",
    "ussgl498100_upward_adjustm_cpe": "USSGL498100_UpwardAdjustmentsOfPriorYearDeliveredOrdersObligationsUnpaid_CPE",
    "obligations_delivered_orde_fyb": "ObligationsDeliveredOrdersUnpaidTotal_FYB",
    "obligations_delivered_orde_cpe": "ObligationsDeliveredOrdersUnpaidTotal_CPE",
    "ussgl480200_undelivered_or_fyb": "USSGL480200_UndeliveredOrdersObligationsPrepaidAdvanced_FYB",
    "ussgl480200_undelivered_or_cpe": "USSGL480200_UndeliveredOrdersObligationsPrepaidAdvanced_CPE",
    "ussgl483200_undelivered_or_cpe": "USSGL483200_UndeliveredOrdersObligationsTransferredPrepaidAdvanced_CPE",
    "ussgl488200_upward_adjustm_cpe": "USSGL488200_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsPrepaidAdvanced_CPE",
    "gross_outlays_undelivered_fyb": "GrossOutlaysUndeliveredOrdersPrepaidTotal_FYB",
    "gross_outlays_undelivered_cpe": "GrossOutlaysUndeliveredOrdersPrepaidTotal_CPE",
    "ussgl490200_delivered_orde_cpe": "USSGL490200_DeliveredOrdersObligationsPaid_CPE",
    "ussgl490800_authority_outl_fyb": "USSGL490800_AuthorityOutlayedNotYetDisbursed_FYB",
    "ussgl490800_authority_outl_cpe": "USSGL490800_AuthorityOutlayedNotYetDisbursed_CPE",
    "ussgl498200_upward_adjustm_cpe": "USSGL498200_UpwardAdjustmentsOfPriorYearDeliveredOrdersObligationsPaid_CPE",
    "gross_outlays_delivered_or_fyb": "GrossOutlaysDeliveredOrdersPaidTotal_FYB",
    "gross_outlays_delivered_or_cpe": "GrossOutlaysDeliveredOrdersPaidTotal_CPE",
    "gross_outlay_amount_by_pro_fyb": "GrossOutlayAmountByProgramObjectClass_FYB",
    "gross_outlay_amount_by_pro_cpe": "GrossOutlayAmountByProgramObjectClass_CPE",
    "obligations_incurred_by_pr_cpe": "ObligationsIncurredByProgramObjectClass_CPE",
    "ussgl487100_downward_adjus_cpe": "USSGL487100_DownwardAdjustmentsOfPriorYearUnpaidUndeliveredOrdersObligationsRecoveries_CPE",
    "ussgl497100_downward_adjus_cpe": "USSGL497100_DownwardAdjustmentsOfPriorYearUnpaidDeliveredOrdersObligationsRecoveries_CPE",
    "ussgl487200_downward_adjus_cpe": "USSGL487200_DownwardAdjustmentsOfPriorYearPrepaidAdvancedUndeliveredOrdersObligationsRefundsCollected_CPE",
    "ussgl497200_downward_adjus_cpe": "USSGL497200_DownwardAdjustmentsOfPriorYearPaidDeliveredOrdersObligationsRefundsCollected_CPE",
    "deobligations_recov_by_pro_cpe": "DeobligationsRecoveriesRefundsdOfPriorYearByProgramObjectClass_CPE",
    "piid": "PIID",
    "parent_award_id": "ParentAwardId",
    "fain": "FAIN",
    "uri": "URI",
    "transaction_obligated_amou": "TransactionObligatedAmount",
    "gross_outlay_amount_by_awa_fyb": "GrossOutlayAmountByAward_FYB",
    "gross_outlay_amount_by_awa_cpe": "GrossOutlayAmountByAward_CPE",
    "obligations_incurred_byawa_cpe": "ObligationsIncurredTotalByAward_CPE",
    "deobligations_recov_by_awa_cpe": "DeobligationsRecoveriesRefundsOfPriorYearByAward_CPE"
}

_AGENCY_TO_TERSE_LABELS = {
    "AllocationTransferAgencyIdentifier": "allocation_transfer_agency",
    "AdjustmentsToUnobligatedBalanceBroughtForward_CPE": "adjustments_to_unobligated_cpe",
    "AgencyIdentifier": "responsible_agency_id",
    "AllocationTransferAgencyIdentifier": "allocation_transfer_agency",
    "AvailabilityTypeCode": "availability_type_code",
    "BeginningPeriodOfAvailability": "beginning_period_of_availa",
    "BorrowingAuthorityAmountTotal_CPE": "borrowing_authority_amount_cpe",
    "BudgetAuthorityAppropriatedAmount_CPE": "budget_authority_appropria_cpe",
    "BudgetAuthorityAvailableAmountTotal_CPE": "budget_authority_available_cpe",
    "BudgetAuthorityUnobligatedBalanceBroughtForward_FYB": "budget_authority_unobligat_fyb",
    "ByDirectReimbursableFundingSource": "by_direct_reimbursable_fun",
    "ContractAuthorityAmountTotal_CPE": "contract_authority_amount_cpe",
    "DeobligationsRecoveriesRefundsByTAS_CPE": "deobligations_recoveries_r_cpe",
    "DeobligationsRecoveriesRefundsdOfPriorYearByProgramObjectClass_CPE": "deobligations_recov_by_pro_cpe",
    "DeobligationsRecoveriesRefundsOfPriorYearByAward_CPE": "deobligations_recov_by_awa_cpe",
    "EndingPeriodOfAvailability": "ending_period_of_availabil",
    "FAIN": "fain",
    "GrossOutlayAmountByAward_CPE": "gross_outlay_amount_by_awa_cpe",
    "GrossOutlayAmountByAward_FYB": "gross_outlay_amount_by_awa_fyb",
    "GrossOutlayAmountByProgramObjectClass_CPE": "gross_outlay_amount_by_pro_cpe",
    "GrossOutlayAmountByProgramObjectClass_FYB": "gross_outlay_amount_by_pro_fyb",
    "GrossOutlayAmountByTAS_CPE": "gross_outlay_amount_by_tas_cpe",
    "GrossOutlaysDeliveredOrdersPaidTotal_CPE": "gross_outlays_delivered_or_cpe",
    "GrossOutlaysDeliveredOrdersPaidTotal_FYB": "gross_outlays_delivered_or_fyb",
    "GrossOutlaysUndeliveredOrdersPrepaidTotal_CPE": "gross_outlays_undelivered_cpe",
    "GrossOutlaysUndeliveredOrdersPrepaidTotal_FYB": "gross_outlays_undelivered_fyb",
    "MainAccountCode": "main_account_code",
    "ObjectClass": "object_class",
    "ObligationsDeliveredOrdersUnpaidTotal_CPE": "obligations_delivered_orde_cpe",
    "ObligationsDeliveredOrdersUnpaidTotal_FYB": "obligations_delivered_orde_fyb",
    "ObligationsIncurredByProgramObjectClass_CPE": "obligations_incurred_by_pr_cpe",
    "ObligationsIncurredTotalByAward_CPE": "obligations_incurred_byawa_cpe",
    "ObligationsIncurredTotalByTAS_CPE": "obligations_incurred_total_cpe",
    "ObligationsUndeliveredOrdersUnpaidTotal_CPE": "obligations_undelivered_or_cpe",
    "ObligationsUndeliveredOrdersUnpaidTotal_FYB": "obligations_undelivered_or_fyb",
    "OtherBudgetaryResourcesAmount_CPE": "other_budgetary_resources_cpe",
    "ParentAwardId": "parent_award_id",
    "PIID": "piid",
    "ProgramActivityCode": "program_activity_code",
    "ProgramActivityName": "program_activity_name",
    "SpendingAuthorityfromOffsettingCollectionsAmountTotal_CPE": "spending_authority_from_of_cpe",
    "StatusOfBudgetaryResourcesTotal_CPE": "status_of_budgetary_resour_cpe",
    "SubAccountCode": "sub_account_code",
    "TransactionObligatedAmount": "transaction_obligated_amou",
    "UnobligatedBalance_CPE": "unobligated_balance_cpe",
    "URI": "uri",
    "USSGL480100_UndeliveredOrdersObligationsUnpaid_CPE": "ussgl480100_undelivered_or_cpe",
    "USSGL480100_UndeliveredOrdersObligationsUnpaid_FYB": "ussgl480100_undelivered_or_fyb",
    "USSGL480200_UndeliveredOrdersObligationsPrepaidAdvanced_CPE": "ussgl480200_undelivered_or_cpe",
    "USSGL480200_UndeliveredOrdersObligationsPrepaidAdvanced_FYB": "ussgl480200_undelivered_or_fyb",
    "USSGL483100_UndeliveredOrdersObligationsTransferredUnpaid_CPE": "ussgl483100_undelivered_or_cpe",
    "USSGL483200_UndeliveredOrdersObligationsTransferredPrepaidAdvanced_CPE": "ussgl483200_undelivered_or_cpe",
    "USSGL487100_DownwardAdjustmentsOfPriorYearUnpaidUndeliveredOrdersObligationsRecoveries_CPE": "ussgl487100_downward_adjus_cpe",
    "USSGL487200_DownwardAdjustmentsOfPriorYearPrepaidAdvancedUndeliveredOrdersObligationsRefundsCollected_CPE": "ussgl487200_downward_adjus_cpe",
    "USSGL488100_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsUnpaid_CPE": "ussgl488100_upward_adjustm_cpe",
    "USSGL488200_UpwardAdjustmentsOfPriorYearUndeliveredOrdersObligationsPrepaidAdvanced_CPE": "ussgl488200_upward_adjustm_cpe",
    "USSGL490100_DeliveredOrdersObligationsUnpaid_CPE": "ussgl490100_delivered_orde_cpe",
    "USSGL490100_DeliveredOrdersObligationsUnpaid_FYB": "ussgl490100_delivered_orde_fyb",
    "USSGL490200_DeliveredOrdersObligationsPaid_CPE": "ussgl490200_delivered_orde_cpe",
    "USSGL490800_AuthorityOutlayedNotYetDisbursed_CPE": "ussgl490800_authority_outl_cpe",
    "USSGL490800_AuthorityOutlayedNotYetDisbursed_FYB": "ussgl490800_authority_outl_fyb",
    "USSGL493100_DeliveredOrdersObligationsTransferredUnpaid_CPE": "ussgl493100_delivered_orde_cpe",
    "USSGL497100_DownwardAdjustmentsOfPriorYearUnpaidDeliveredOrdersObligationsRecoveries_CPE": "ussgl497100_downward_adjus_cpe",
    "USSGL497200_DownwardAdjustmentsOfPriorYearPaidDeliveredOrdersObligationsRefundsCollected_CPE": "ussgl497200_downward_adjus_cpe",
    "USSGL498100_UpwardAdjustmentsOfPriorYearDeliveredOrdersObligationsUnpaid_CPE": "ussgl498100_upward_adjustm_cpe",
    "USSGL498200_UpwardAdjustmentsOfPriorYearDeliveredOrdersObligationsPaid_CPE": "ussgl498200_upward_adjustm_cpe"
}

# How the response is grouped
_RESPONSE_MAP = {
    "budget_authority_unobligat_fyb": "Budget Authority",
    "unobligated_balance_cpe": "Unobligated Balance - Total",
    "deobligations_recoveries_r_cpe": "Unobligated Balance - Total",
    "treasury_account_identifier": "TAS Component",
    "sub_account_code": "TAS Component",
    "responsible_agency_id": "TAS Component",
    "main_account_code": "TAS Component",
    "ending_period_of_availabil": "TAS Component",
    "beginning_period_of_availa": "TAS Component",
    "availability_type_code": "TAS Component",
    "allocation_transfer_agency_id": "TAS Component",
    "status_of_budgetary_resour_cpe": "Status of Budgetary Resources - Total",
    "reporting_period_start": "Reporting Period",
    "reporting_period_end": "Reporting Period",
    "program_activity_name": "Program Activity, Object Class, Direct Reimbursable",
    "program_activity_code": "Program Activity, Object Class, Direct Reimbursable",
    "object_class": "Program Activity, Object Class, Direct Reimbursable",
    "by_direct_reimbursable_fun": "Program Activity, Object Class, Direct Reimbursable",
    "spending_authority_from_of_cpe": "Other Budgetary Resources",
    "contract_authority_amount_cpe": "Other Budgetary Resources",
    "borrowing_authority_amount_cpe": "Other Budgetary Resources",
    "ussgl488100_upward_adjustm_cpe": "Obligations Undelivered Orders Unpaid",
    "ussgl483100_undelivered_or_cpe": "Obligations Undelivered Orders Unpaid",
    "ussgl480100_undelivered_or_fyb": "Obligations Undelivered Orders Unpaid",
    "ussgl480100_undelivered_or_cpe": "Obligations Undelivered Orders Unpaid",
    "obligations_undelivered_or_fyb": "Obligations Undelivered Orders Unpaid",
    "obligations_undelivered_or_cpe": "Obligations Undelivered Orders Unpaid",
    "obligations_incurred_total_cpe": "Obligations Incurred - Total by TAS",
    "gross_outlay_amount_by_tas_cpe": "Obligations Incurred - Total by TAS",
    "obligations_incurred_by_pr_cpe": "Obligations Incurred - Total by Program, Object Class",
    "ussgl498100_upward_adjustm_cpe": "Obligations Delivered Orders Unpaid",
    "ussgl493100_delivered_orde_cpe": "Obligations Delivered Orders Unpaid",
    "ussgl490100_delivered_orde_fyb": "Obligations Delivered Orders Unpaid",
    "ussgl490100_delivered_orde_cpe": "Obligations Delivered Orders Unpaid",
    "obligations_delivered_orde_fyb": "Obligations Delivered Orders Unpaid",
    "obligations_delivered_orde_cpe": "Obligations Delivered Orders Unpaid",
    "ussgl488200_upward_adjustm_cpe": "Gross Outlays Undelivered Orders Prepaid",
    "ussgl483200_undelivered_or_cpe": "Gross Outlays Undelivered Orders Prepaid",
    "ussgl480200_undelivered_or_fyb": "Gross Outlays Undelivered Orders Prepaid",
    "ussgl480200_undelivered_or_cpe": "Gross Outlays Undelivered Orders Prepaid",
    "gross_outlays_undelivered_fyb": "Gross Outlays Undelivered Orders Prepaid",
    "gross_outlays_undelivered_cpe": "Gross Outlays Undelivered Orders Prepaid",
    "gross_outlays_delivered_or_fyb": "Gross Outlays Delivered Orders Prepaid",
    "gross_outlays_delivered_or_cpe": "Gross Outlays Delivered Orders Prepaid",
    "ussgl498200_upward_adjustm_cpe": "Gross Outlays Delivered Orders Paid",
    "ussgl490800_authority_outl_fyb": "Gross Outlays Delivered Orders Paid",
    "ussgl490800_authority_outl_cpe": "Gross Outlays Delivered Orders Paid",
    "ussgl490200_delivered_orde_cpe": "Gross Outlays Delivered Orders Paid",
    "gross_outlay_amount_by_pro_fyb": "Gross Outlay Amount by Program Object Class",
    "gross_outlay_amount_by_pro_cpe": "Gross Outlay Amount by Program Object Class",
    "ussgl497200_downward_adjus_cpe": "Deobligations Recoveries Refunds of Prior Year by Program Object Class",
    "ussgl497100_downward_adjus_cpe": "Deobligations Recoveries Refunds of Prior Year by Program Object Class",
    "ussgl487200_downward_adjus_cpe": "Deobligations Recoveries Refunds of Prior Year by Program Object Class",
    "ussgl487100_downward_adjus_cpe": "Deobligations Recoveries Refunds of Prior Year by Program Object Class",
    "deobligations_recov_by_pro_cpe": "Deobligations Recoveries Refunds of Prior Year by Program Object Class",
    "other_budgetary_resources_cpe": "Budget Authority",
    "budget_authority_unobligat_fyb": "Budget Authority",
    "budget_authority_available_cpe": "Budget Authority",
    "budget_authority_appropria_cpe": "Budget Authority",
    "adjustments_to_unobligated_cpe": "Budget Authority"
}
